### ISSUE TITLE
Cryptococcus NTR: mating efficiency phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#116]
NTR
1)  mating efficiency phenotype (is_a mating phenotype) - see  #119 for mating phenotype issue.
APO cross-refs:
id: APO:0000034
name: mating efficiency
namespace: observable
alt_id: YPO:0000034
def: "The proportion of cells within a population that are able to mate." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000032 ! mating response

2)  altered mating efficiency (is_a mating efficiency phenotype)
3)  increased mating efficiency (is_a altered mating efficiency)
4)  decreased mating efficiency (is_a altered mating efficiency)
5)  increased rate of mating efficiency (is_a altered mating efficiency)
6)  decreased rate of mating efficiency (is_a altered mating efficiency)

**Comment by Jguzman210** [comment]
OMP:0005356	mating efficiency phenotype
OMP:0005357	altered mating efficiency
OMP:0005358	increased mating efficiency
OMP:0005359	decreased mating efficiency

**Comment by dsiegele** [comment]
Following the example of FYPO, I asked Jesus to make the mating efficiency phenotype terms be children of sexual reproduction phenotype (OMP:0007406) instead of mating phenotype (OMP:0007412). The reason for this is that depending on the assay used, a change in measured mating efficiency may reflect a change in conjugation frequency (see OMP:0007412 mating phenotype and its descendants) and/or a change in some other biological process such as sexual sporulation (see OMP:0007045 and its descendants). This explanation is included as a comment on the mating efficiency terms.
