### ISSUE TITLE
Cryptococcus NTR: mating phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#119]
NTR

1)  mating phenotype
xref: GO:0007618 " mating"

2)  presence of mating (is_a mating phenotype)
3)  absence of mating (is_a mating phenotype)
4)  altered mating (is_a mating phenotype)
5)  increased mating (is_a altered mating)
6)  decreased mating (is_a altered mating)
7)  delayed mating (is_a altered mating)

**Comment by dianeoinglis** [comment]
"Mating phenotype" is good for Cryptococcus. "Mating efficiency" should be a child term and is mostly used when the assay is quantitative. Mating can also be abnormal so "altered mating phenotype" should also be created.

Diane

**Comment by Achchuthan** [comment]
Thanks Diane for your comment! There is another issue for "mating efficiency" phenotype and I referenced this issue as the parent term now. See #116

**Comment by dsiegele** [comment]
I reviewed the organization of sexual reproduction terms in GO and also looked at how mating phenotype terms in FYPO are cross-referenced to GO. Based on my review, I think the appropriate cross reference for OMP:0007412 ! mating phenotype is GO:0000747 ! conjugation with cell fusion instead of GO:0007618 ! mating. Based on its child terms, I think that [GO:0007618](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0007618_!_mating) is meant to be used to annotate mating processes that occur between multicellular organisms. 

GO:0000747 ! conjugation with cell fusion 
def. A conjugation process that results in the union of cellular and genetic information from compatible mating types. An example of this process is found in Saccharomyces cerevisiae.

FYPO:0000301 ! mating phenotype 
def. A biological process phenotype that affects conjugation.
is_a: FYPO:0000114 ! cellular process phenotype
intersection_of: FYPO:0000001 ! phenotype
intersection_of: inheres_in GO:0000747 ! conjugation with cellular fusion
relationship: inheres_in GO:0000747 ! conjugation with cellular fusion

OMP:0007412 ! mating phenotype
def. A sexual reproduction phenotype that affects conjugation, which is the union of cellular and genetic information from two organisms of compatible mating types.

Issue #118  requests terms for mating response phenotypes. I think that APO:0000032 ! mating response (def. The interaction between organisms leading to mating.) would be a synonym of OMP:0007412 ! mating phenotype. Can we merge issues #118 and #119? Let me know if I'm overlooking something.

**Comment by Jguzman210** [comment]
OMP:0005355	abolished mating
OMP:0005351	absence of mating
OMP:0005352	altered mating
OMP:0005354	decreased mating
OMP:0005353	increased mating
OMP:0007412	mating phenotype
OMP:0005350	presence of mating

**Comment by dianeoinglis** [comment]
Hi Debby, as for the observable phenotype in Cryptococcus and other fungal species, the actual response is initially to a compatable pheromone. The entire mating process is not necessarily followed all the way. The most appropriate term is not "mating response" but is a pheromone response. Shall "response to pheromone phenotype" or pheromone response phenotype" be a seperate request?
Diane
