### ISSUE TITLE
Cryptococcus NTR: morphology phenotype

### ISSUE THREAD

**Issue by Achchuthan** [microbialphenotypes/OMP-ontology#124]
NTR

1)	morphology phenotype
APO cross-refs:
id: APO:0000049
name: morphology
namespace: observable
alt_id: YPO:0000049
def: "The size or shape of subcellular structures, cells, or multicellular structures." [SGD:mcc]
subset: AspGD
subset: CGD
subset: CryptoGD
subset: SGD
is_a: APO:0000017 ! observable

2)	altered morphology (is_a morphology phenotype)

**Comment by dianeoinglis** [comment]
Can we modify this term request to be specific for "cell morphology" or "cellular morphology?" That is the specific pheotype that is referred to here.

"While wild-type cells are spherical, the mutant cells appeared to have collapsed in on themselves, manifested as membrane staining in either crescent shapes or double rings depending on cell orientation. This aberrant morphology occurred whether the fungi were inside macrophages (Fig 2A) or grown independently (Fig 2B), indicating that the alteration is intrinsic to the mutant rather than induced by the host cells."

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4430228/
http://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1004908

Thank you,
Diane

**Comment by Achchuthan** [comment]
Cell morphology already exists. So, I'm closing this issue!
