### ISSUE TITLE
Cryptococcus NTR agar invasion phenotype

### ISSUE THREAD

**Issue by dianeoinglis** [microbialphenotypes/OMP-ontology#188]
Replaces NTR for "invasive growth phenotype" #114. Self-explanatory phenotype except that growth is typically tested under a starvation condition such as low-ammonium or low-glucose.

'agar invasion phenotype'
'altered agar invasion phenotype'
'increased agar invasion phenotype'
'decreased agar invasion phenotype'
'abolished agar invasion phenotype"

**Comment by dianeoinglis** [comment]
These are great. Please create them.

Thank you!
Diane

**Comment by dsiegele** [comment]
Diane,

I asked Jesus to add the following terms to the ontology. I didn't include specific growth conditions in the definition because those won't be the same for all microbes that can invade agar during growth. Medium composition, temperature, and other experimental conditions can be indicated in the environment field and/or connecting to an ECO term.

I look forward to your comments.

Regards,

Debby 

agar invasion phenotype: A growth phenotype relating to the ability of a microbe to penetrate agar media during growth. 

presence of agar invasion: An agar invasion phenotype where a microbe has the ability to penetrate agar media during growth.
     narrow synonym--APO:0000028: Penetration of cells into a solid substrate during filamentous growth

absence of agar invasion: An agar invasion phenotype where a microbe lacks the ability to penetrate agar media during growth.

altered agar invasion: An agar invasion phenotype where the frequency, rate, timing, or extent of agar invasion is altered relative to a designated control.

increased agar invasion: An altered agar invasion phenotype where the frequency, rate, timing, or extent of agar invasion is increased relative to a designated control.

decreased agar invasion phenotype: An altered agar invasion phenotype where the frequency, rate, timing, or extent of agar invasion is decreased relative to a designated control.

abolished agar invasion: A decreased agar invasion phenotype where the ability to invade agar media is abolished.

**Comment by Jguzman210** [comment]
uploaded to OMP!

**Comment by dianeoinglis** [comment]
Hi,

Can the OMP IDs be noted in this tracker issue?

Thank you,
Diane

**Comment by dsiegele** [comment]
Hi Diane,

OMP:0005325	agar invasion phenotype
.....OMP:0005326 presence of agar invasion
.....OMP:0005327 absence of agar invasion
.....OMP:0005328 altered agar invasion
..........OMP:0005329 increased agar invasion
..........OMP:0005330 decreased agar invasion
...............OMP:0005331 abolished agar invasion

Sorry for the oversight. I also added the OMP IDs to the earlier post with the definitions.

Debby

**Comment by dianeoinglis** [comment]
Hi Debby,

These look great. I agree the specific growth conditions do not need to be included in the def as they  will be different across species.
